import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { Sparkles, Terminal, Play, CheckCircle2, AlertTriangle, ArrowRight, Loader2 } from "lucide-react";

export function StrategyLab() {
  const { user } = useAuth();
  const [prompt, setPrompt] = useState("");
  const [stage, setStage] = useState<"input" | "generating" | "spec" | "backtesting" | "result">("input");
  const [showUpgradeModal, setShowUpgradeModal] = useState(false);

  // Simulated strategy SPEC generated by AI
  const simulatedSpec = `version: "v22"
indicators:
  - type: "RSI"
    period: 14
    timeframe: "4H"
    oversold: 30
    overbought: 70
  - type: "EMA"
    periods: [20, 50]
    timeframe: "15m"
rules:
  entry:
    trigger: "RSI <= 30 AND macro_trend == 'bullish'"
  exit:
    trigger: "EMA_20 crosses_under EMA_50"
risk_management:
  stop_loss: "1.5 * ATR(14)"
  take_profit: "3.5 * ATR(14)"`;

  // Dynamic limits check for Free Tier
  const tierConfig = {
    free: { limit: 1, label: "Free Tier" },
    explorer: { limit: 3, label: "Explorer Tier" },
    trader: { limit: 10, label: "Trader Tier" },
    pro: { limit: 50, label: "Pro Tier" },
    auto: { limit: 9999, label: "Auto Tier" },
  };

  const currentLimit = user ? tierConfig[user.tier].limit : 1;
  const isAtLimit = currentLimit === 1; // On free tier, they can only run 1 active strategy.

  function handleBuild() {
    if (!prompt.trim()) return;
    setStage("generating");
    setTimeout(() => {
      setStage("spec");
    }, 2500); // 2.5s simulated AI compiler
  }

  function handleRunBacktest() {
    if (isAtLimit) {
      setShowUpgradeModal(true);
      return;
    }
    setStage("backtesting");
    setTimeout(() => {
      setStage("result");
    }, 3000); // 3s simulated backtest run
  }

  return (
    <div className="space-y-6 pt-4">
      {/* ── HEADER TITLE ── */}
      <div className="flex items-center gap-2.5">
        <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-accent/15 text-accent">
          <Sparkles className="h-5 w-5 animate-pulse" />
        </div>
        <div>
          <h1 className="text-xl font-extrabold text-ink">AI Strategy Lab</h1>
          <p className="text-xs text-ink-muted mt-0.5">Describe your idea. The AI builds and simulates it offline.</p>
        </div>
      </div>

      {/* ── STAGE 1: PROMPT INPUT ── */}
      {stage === "input" && (
        <div className="space-y-4 animate-fade-in">
          <div className="card p-5 bg-bg-card/40 border-line/60">
            <label className="block text-xs font-bold uppercase tracking-wider text-ink-subtle">
              What idea would you like to test?
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. Buy Bitcoin on the 4H chart when the RSI is oversold under 30. Set a Stop Loss at 1.5 ATR and exit when the 20 EMA crosses below the 50 EMA on the 15m chart..."
              rows={5}
              className="mt-3 block w-full rounded-xl border border-line bg-bg-elev/40 p-4 text-sm text-ink placeholder-ink-subtle outline-none focus:border-accent resize-none transition-colors"
            />
            <button
              onClick={handleBuild}
              disabled={!prompt.trim()}
              className="btn-primary w-full mt-4 py-3.5 shadow-md shadow-accent/20"
            >
              Build Strategy Spec
              <ArrowRight className="h-4 w-4" />
            </button>
          </div>

          {/* Quick templates */}
          <div className="space-y-2">
            <span className="text-[10px] font-bold uppercase tracking-wider text-ink-subtle">Popular templates</span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <button
                onClick={() => setPrompt("RSI oversold strategy on Ethereum. Enter when 4-hour RSI crosses below 30 and MACD is crossing bullish on 1H. Exits at 2.5 Risk-to-Reward ratio.")}
                className="card p-3 bg-bg-card/25 border-line/40 hover:border-accent/40 text-left text-xs font-semibold text-ink-muted hover:text-ink active:scale-95 transition-all"
              >
                📊 ETH Pullback Strategy
              </button>
              <button
                onClick={() => setPrompt("Golden cross breakout on Solana. Buy when 50 EMA crosses above 200 EMA on the 1-day chart. Exit immediately if daily close crosses below 20 EMA.")}
                className="card p-3 bg-bg-card/25 border-line/40 hover:border-accent/40 text-left text-xs font-semibold text-ink-muted hover:text-ink active:scale-95 transition-all"
              >
                📈 SOL Trend Breakout
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── STAGE 2: GENERATING SPECS ── */}
      {stage === "generating" && (
        <div className="card p-12 bg-bg-card/40 flex flex-col items-center justify-center text-center animate-fade-in border-line/60">
          <Loader2 className="h-10 w-10 animate-spin text-accent mb-4" />
          <h3 className="font-bold text-ink">Claude compiling your logic...</h3>
          <p className="text-xs text-ink-muted mt-2 max-w-xs leading-relaxed">
            Parsing indicators, mapping triggers, and structuring rules into an executable JSON/YAML specification.
          </p>
        </div>
      )}

      {/* ── STAGE 3: SPEC VIEW ── */}
      {stage === "spec" && (
        <div className="space-y-4 animate-fade-in">
          <div className="card p-4 bg-bg-card/45 border-line/60">
            <div className="flex items-center gap-2 text-xs font-semibold text-ink-subtle uppercase tracking-wider mb-3">
              <Terminal className="h-4 w-4" />
              Generated Spec (YAML)
            </div>
            <pre className="rounded-xl bg-bg-elev/60 p-4 font-mono text-[10px] text-accent/90 border border-line/40 leading-relaxed overflow-x-auto select-all">
              {simulatedSpec}
            </pre>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => setStage("input")}
              className="btn-ghost flex-1 py-3.5 border-line/50 hover:bg-bg-elev"
            >
              Re-edit Prompt
            </button>
            <button
              onClick={handleRunBacktest}
              className="btn-primary flex-1 py-3.5 shadow-md shadow-accent/20"
            >
              Run Backtest Simulator
              <Play className="h-4 w-4 fill-bg" />
            </button>
          </div>
        </div>
      )}

      {/* ── STAGE 4: BACKTEST RUNNING ── */}
      {stage === "backtesting" && (
        <div className="card p-12 bg-bg-card/40 flex flex-col items-center justify-center text-center animate-fade-in border-line/60">
          <Loader2 className="h-10 w-10 animate-spin text-accent mb-4" />
          <h3 className="font-bold text-ink">Simulating Backtest...</h3>
          <p className="text-xs text-ink-muted mt-2 max-w-xs leading-relaxed">
            Running compiled strategy rules across <strong className="text-ink">8 years</strong> of historical minute data (47 trading pairs).
          </p>
        </div>
      )}

      {/* ── STAGE 5: RESULT VIEW ── */}
      {stage === "result" && (
        <div className="space-y-4 animate-fade-in">
          {/* Audit Verification status */}
          <div className="flex items-center justify-between rounded-xl bg-emerald-500/10 border border-emerald-500/20 px-3.5 py-2.5">
            <div className="flex items-center gap-2 text-xs font-bold text-emerald-400">
              <CheckCircle2 className="h-4.5 w-4.5" />
              Walk-forward Audit Passed
            </div>
            <span className="rounded bg-emerald-500/25 px-2 py-0.5 text-[9px] font-extrabold uppercase text-emerald-400 tracking-wider">
              Robust
            </span>
          </div>

          {/* Result Card */}
          <div className="card p-5 bg-bg-card/40 border-line/60 space-y-6">
            <div className="grid grid-cols-3 gap-2 text-center divide-x divide-line/30">
              <div>
                <div className="text-[10px] font-bold text-ink-subtle uppercase">PnL Return</div>
                <div className="text-lg font-extrabold text-accent mt-1 tabular-nums">+784%</div>
              </div>
              <div>
                <div className="text-[10px] font-bold text-ink-subtle uppercase">Win-Rate</div>
                <div className="text-lg font-extrabold text-ink mt-1 tabular-nums">49.2%</div>
              </div>
              <div>
                <div className="text-[10px] font-bold text-ink-subtle uppercase">Max Drawdown</div>
                <div className="text-lg font-extrabold text-red-400 mt-1 tabular-nums">8.57%</div>
              </div>
            </div>

            {/* Custom SVG Equity Curve Line Chart */}
            <div className="space-y-2">
              <span className="text-[10px] font-bold uppercase tracking-wider text-ink-subtle">Equity curve</span>
              <div className="rounded-xl bg-bg-elev/40 border border-line/40 p-4 h-32 flex items-center justify-center relative overflow-hidden">
                <svg
                  className="absolute inset-0 w-full h-full p-2"
                  viewBox="0 0 100 100"
                  preserveAspectRatio="none"
                >
                  <defs>
                    <linearGradient id="equity-gradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="#22d3aa" stopOpacity="0.25" />
                      <stop offset="100%" stopColor="#22d3aa" stopOpacity="0.0" />
                    </linearGradient>
                  </defs>
                  {/* Grid Lines */}
                  <line x1="0" y1="25" x2="100" y2="25" stroke="#1e2740" strokeWidth="0.25" strokeDasharray="2,2" />
                  <line x1="0" y1="50" x2="100" y2="50" stroke="#1e2740" strokeWidth="0.25" strokeDasharray="2,2" />
                  <line x1="0" y1="75" x2="100" y2="75" stroke="#1e2740" strokeWidth="0.25" strokeDasharray="2,2" />
                  
                  {/* Fill Area */}
                  <path
                    d="M0,90 Q15,85 25,65 T50,55 T75,25 T100,10 L100,100 L0,100 Z"
                    fill="url(#equity-gradient)"
                  />
                  {/* Chart Line */}
                  <path
                    d="M0,90 Q15,85 25,65 T50,55 T75,25 T100,10"
                    fill="none"
                    stroke="#22d3aa"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                  />
                </svg>
              </div>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => setStage("input")}
              className="btn-ghost flex-1 py-3.5 border-line/50 hover:bg-bg-elev"
            >
              Simulate Another
            </button>
            <button
              onClick={() => alert("Simulation added to your Dashboard!")}
              className="btn-primary flex-1 py-3.5 shadow-md shadow-accent/20"
            >
              Save Strategy
            </button>
          </div>
        </div>
      )}

      {/* ── PREMIUM UPGRADE DRAWER / MODAL ── */}
      {showUpgradeModal && (
        <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 backdrop-blur-sm p-4 animate-fade-in">
          <div className="w-full max-w-md rounded-3xl border border-line bg-bg-card p-6 shadow-2xl animate-slide-up">
            <div className="flex flex-col items-center text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-accent/10 text-accent mb-4">
                <AlertTriangle className="h-6 w-6 text-accent animate-pulse" />
              </div>
              <h3 className="text-lg font-bold text-ink">Unlock Priority Backtests</h3>
              <p className="text-sm text-ink-muted mt-2 px-4">
                Free plan users are limited to <strong className="text-ink">1 active backtest/strategy</strong>. Upgrade to Explorer ($19/mo) to unlock:
              </p>

              <div className="w-full mt-6 space-y-3 text-left bg-bg-elev/40 rounded-2xl p-4 border border-line/40">
                <div className="flex items-center gap-2.5 text-xs text-ink">
                  <CheckCircle2 className="h-4.5 w-4.5 text-accent flex-none" />
                  <span><strong>Unlimited</strong> draft strategies in your list</span>
                </div>
                <div className="flex items-center gap-2.5 text-xs text-ink">
                  <CheckCircle2 className="h-4.5 w-4.5 text-accent flex-none" />
                  <span><strong>Instant</strong> multi-threaded backtest engine</span>
                </div>
                <div className="flex items-center gap-2.5 text-xs text-ink">
                  <CheckCircle2 className="h-4.5 w-4.5 text-accent flex-none" />
                  <span>Full trade-by-trade CSV exports</span>
                </div>
              </div>

              <div className="w-full mt-6 space-y-3">
                <button
                  onClick={() => alert("Simulated Stripe checkout!")}
                  className="btn-primary w-full py-3.5 shadow-lg shadow-accent/20"
                >
                  Upgrade for $19/month
                </button>
                <button
                  onClick={() => setShowUpgradeModal(false)}
                  className="btn-ghost w-full py-3.5 border-none"
                >
                  Maybe Later
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
