-- ============================================================================
-- Strategy Labs — Blogs Schema (v2)
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- 6.  BLOGS — auto-posted AI backtest breakdown reports & research blogs
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists public.blogs (
  id              uuid          primary key default uuid_generate_v4(),
  title           text          not null,
  slug            text          not null unique,
  excerpt         text          not null,
  content         text          not null,
  cover_gradient  text          not null default 'from-[#22d3aa]/30 via-[#3b6af1]/25 to-bg-card',
  read_time       text          not null default '5 min read',
  tags            text[]        not null default '{}',
  created_at      timestamptz   not null default now(),
  updated_at      timestamptz   not null default now()
);

comment on table public.blogs is 'Quantitative research blog posts, auto-generated by the AI pipeline.';

create index if not exists blogs_slug_idx       on public.blogs (slug);
create index if not exists blogs_created_at_idx on public.blogs (created_at desc);

alter table public.blogs enable row level security;

-- Anyone (anon and authenticated) can read blogs
drop policy if exists "anyone can read blogs" on public.blogs;
create policy "anyone can read blogs"
  on public.blogs for select
  to anon, authenticated
  using (true);

-- Trigger for touch_updated_at
drop trigger if exists blogs_updated on public.blogs;
create trigger blogs_updated
  before update on public.blogs
  for each row execute procedure public.touch_updated_at();
